sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.3.3
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v 1.14.6
script:
  - bundle _1.14.6_ exec rake
